version: '3'

networks:
  nginx_proxy_manager:

services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    container_name: nginx-proxy-manager
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - nginxproxymanager:/data
      - letsencrypt:/etc/letsencrypt
    networks:
      nginx_proxy_manager:

  portainer-ce:
    ports:
      - 9000:9000
      - 8000:8000
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    image: portainer/portainer-ce:latest
    networks:
      nginx_proxy_manager:
      
volumes:
  portainer_data:
  nginxproxymanager:
  letsencrypt:
